### ISSUE TITLE
Update Python packages

### ISSUE THREAD

**Issue by Doralitze** [c3foc/hagrid#35]
Some python packages (at least django) received some major (security-) updates since the versions pinned inside `requirements.txt`. These packages need to be updated to the next secure version and one needs to check the functionality of the website after each update. (The last one would also be a great opportunity in order to write some propper unit tests.)

**Comment by felixrindt** [comment]
Can you say exactly which packages need to be updated? As of today, I did not find a newer version for django ([`3.0.2`](https://www.djangoproject.com/download/)) than the one currently pinned in requirements (`>=3.0, <3.1`).
