### ISSUE TITLE
Show Info line in packing pdf

### ISSUE THREAD

**Issue by Doralitze** [c3foc/hagrid#7]
The code responsible for rendering the info strip doesn't do so.

**Comment by felixrindt** [comment]
What is "info line"?

**Comment by felixrindt** [comment]
And remember that we haven't merged the exporter yet.

**Comment by Doralitze** [comment]
> What is "info line"?

The info line was a line on the left side of each page on the old software containing a human readable reservation reference (ID), time of print and reservation state

**Comment by Doralitze** [comment]
Fixed as of commit 67b2a74.
