### ISSUE TITLE
Reprint table header on packing pdf

### ISSUE THREAD

**Issue by Doralitze** [c3foc/hagrid#8]
The packing table header needs to be reprinted when the packing table reaches a new packing section. It should also be reprinted if there was a page break and a new packing section shouldn't be started when it would only contain the header on the current page.

**Comment by Doralitze** [comment]
This really depends on issue #12 right now as the setting in the model whether or not the teams want their order split up or not in order to decide if splitting the packing list is necessary or not.

**Comment by Doralitze** [comment]
I think I'll work on this one next.

**Comment by felixrindt** [comment]
#12 has just been closed.

**Comment by Doralitze** [comment]
As the PR is merged now, this issue is dealt with
